### ISSUE TITLE
Oxford English vs British English

### ISSUE THREAD

**Issue by mzuenni** [nwerc/docs#1]
Do we prefer [Oxford English](https://en.wikipedia.org/wiki/Oxford_spelling) or British English i.e. do we want to write _realize_ or _realise_?

**Comment by mpsijm** [comment]
To be fair, I did not even know that this distinction existed, but interesting discussion point :smile: 

~~So far~~ In the contests that I've been involved in, we have used British English, purely based on the fact that I have set my spell-checkers to British English. In fact, it looks like I have explicitly disabled the Oxford spelling rule in IntelliJ to prefer "-ise" (see screenshot) :joy: 

<details>
<summary>IntelliJ Settings Screenshot</summary>

![image](https://github.com/nwerc/docs/assets/9739541/1645375e-73ac-4e0b-b303-0e1b218a4335)

</details>

I think I would be fine with either, as long as we're consistent across contests. This argument would currently give the edge to British English, I think, since that's what we've been using (or trying to use) so far.

And initially, I thought that using Oxford English in automated spell-checkers would be more difficult, but with a quick check, it looks like it is supported in at least VS Code and Chrome (besides IntelliJ), so that's not a valid argument in that case :stuck_out_tongue:

**Comment by mzuenni** [comment]
We have used both styles in previous nwercs:

- maximised in https://2022.nwerc.eu/main/problem-set.pdf
- minimize in https://2021.nwerc.eu/files/nwerc2021problems.pdf

My personal taste would be to use oxford english in this case.

**Comment by paul-wild** [comment]
I was not aware that this is what it's called, but Oxford English is also my preferred spelling.

**Comment by RagnarGrootKoerkamp** [comment]
I also slightly lean towards Oxford English
